let playMode='local';
let deck=[],index=0,stage='owner',selected=null,secretAnswer=null;
let p1='أنت',p2='حبيبك',score=[0,0],attempts=[0,0],owner=0,guesser=1;
let peer=null,conn=null,isHost=false,myIndex=0,roomCode='',connected=false;
let onlinePhase='idle';

function showScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function openOnline(){showScreen('onlineSetup')}
function openLocal(){showScreen('localSetup')}
function goHome(){cleanupPeer();showScreen('home')}
function exitGame(){cleanupPeer();resetState();showScreen('home')}
function resetState(){deck=[];index=0;stage='owner';selected=null;secretAnswer=null;score=[0,0];attempts=[0,0];owner=0;guesser=1;onlinePhase='idle';document.getElementById('meterFill').style.width='0';}
function cleanupPeer(){try{if(conn)conn.close()}catch(e){}try{if(peer)peer.destroy()}catch(e){}conn=null;peer=null;connected=false;roomCode='';isHost=false;}
function esc(s){return String(s).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a;}
function getFreshDeck(pool,size){const key='hal_taarifni_used_v3';let used=[];try{used=JSON.parse(localStorage.getItem(key)||'[]')}catch(e){}const fresh=pool.filter(x=>!used.includes(x.q));let chosen=fresh.length>=size?shuffle(fresh).slice(0,size):shuffle(fresh).concat(shuffle(pool.filter(x=>!fresh.includes(x))).slice(0,size-fresh.length));try{localStorage.setItem(key,JSON.stringify([...used,...chosen.map(x=>x.q)].slice(-80)))}catch(e){}return chosen;}
function updateScores(){document.getElementById('score1').textContent='💗 '+p1+': '+score[0];document.getElementById('score2').textContent='💜 '+p2+': '+score[1];document.getElementById('counter').textContent='السؤال '+(Math.min(index+1,deck.length))+' من '+deck.length;document.getElementById('progressBar').style.width=(((Math.min(index+1,deck.length))/Math.max(1,deck.length))*100)+'%';}
function setTurn(text){document.getElementById('turnBanner').innerHTML=text;}
function showReaction(ok){const r=document.getElementById('reaction'),card=document.getElementById('gameCard');r.textContent=ok?'❤️ +1':'💔';r.classList.remove('pop');card.classList.remove('celebrate','oops');void r.offsetWidth;r.classList.add('pop');card.classList.add(ok?'celebrate':'oops');setTimeout(()=>card.classList.remove('celebrate','oops'),700);}
function renderAnswers(enabled=true){const h=document.getElementById('answers');h.innerHTML='';deck[index].a.forEach((ans,i)=>{const b=document.createElement('button');b.type='button';b.className='answer';b.textContent=ans;b.disabled=!enabled;b.dataset.index=i;b.addEventListener('click',()=>selectAnswer(i,b));h.appendChild(b);});}
function setMainButton(text,ready=false){const b=document.getElementById('mainBtn');b.textContent=text;b.disabled=false;b.style.pointerEvents='auto';b.classList.toggle('ready',ready);b.setAttribute('aria-disabled','false');}
function selectAnswer(i,el){selected=i;document.querySelectorAll('.answer').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');const b=document.getElementById('mainBtn');b.disabled=false;b.style.pointerEvents='auto';b.classList.add('ready');b.setAttribute('aria-disabled','false');}
function needChoice(){const fb=document.getElementById('feedback');fb.style.display='block';fb.className='feedback bad';fb.textContent='اختار/ي إجابة أولًا ثم اضغط/ي الزر 💗';fb.scrollIntoView({behavior:'smooth',block:'nearest'});}
function showQuestionStage(){document.getElementById('questionStage').style.display='block';document.getElementById('waiting').style.display='none';document.getElementById('feedback').style.display='none';}
function showWaiting(title,text,icon='💌'){document.getElementById('questionStage').style.display='none';document.getElementById('waiting').style.display='block';document.getElementById('waitingTitle').textContent=title;document.getElementById('waitingText').innerHTML=text;document.getElementById('waitingIcon').textContent=icon;}

function startLocal(){playMode='local';p1=document.getElementById('p1').value.trim()||'اللاعب الأول';p2=document.getElementById('p2').value.trim()||'اللاعب الثاني';const mode=document.getElementById('mode').value,size=+document.getElementById('roundSize').value,pool=mode==='all'?bank:bank.filter(x=>x.c===mode);deck=getFreshDeck(pool,Math.min(size,pool.length));score=[0,0];attempts=[0,0];index=0;owner=Math.random()<.5?0:1;guesser=1-owner;showScreen('game');renderLocalOwner();}
function renderLocalOwner(){stage='owner';selected=null;secretAnswer=null;showQuestionStage();setTurn('💞 دور <strong>'+(owner===0?esc(p1):esc(p2))+'</strong> الآن — السؤال '+(index+1)+' من '+deck.length);document.getElementById('stepBadge').textContent='إجابة سرّية 🔒';document.getElementById('question').textContent=deck[index].q;const n=owner===0?p1:p2;document.getElementById('instruction').innerHTML='<strong>'+esc(n)+'</strong> اختار/ي إجابتك الحقيقية بدون ما الطرف الثاني يشوفها.';renderAnswers(true);setMainButton('ثبّت الإجابة 🔒',false);updateScores();}
function localLock(){if(selected===null){needChoice();return}secretAnswer=selected;selected=null;const n=guesser===0?p1:p2;showWaiting('خبّينا الإجابة 🙈','سلّموا الجهاز الآن إلى <strong>'+esc(n)+'</strong>، وبعدها اضغط/ي هنا للمتابعة.','🙈💌');const w=document.getElementById('waiting');w.onclick=()=>{w.onclick=null;localBeginGuess()};w.style.cursor='pointer';document.getElementById('waitingText').innerHTML+=' <br><br><strong>اضغط/ي هنا عندما يصبح '+esc(n)+' جاهزًا.</strong>';}
function localBeginGuess(){stage='guess';selected=null;showQuestionStage();setTurn('💭 دور <strong>'+(guesser===0?esc(p1):esc(p2))+'</strong> للتخمين — السؤال '+(index+1)+' من '+deck.length);document.getElementById('stepBadge').textContent='خمن الإجابة 💭';document.getElementById('question').textContent=deck[index].q;const g=guesser===0?p1:p2,o=owner===0?p1:p2;document.getElementById('instruction').innerHTML='<strong>'+esc(g)+'</strong>، ما الإجابة التي تتوقع أن '+esc(o)+' اختارها؟';renderAnswers(true);setMainButton('أكد التخمين 💘',false);}
function localCheck(){if(selected===null){needChoice();return}stage='result';const buttons=[...document.querySelectorAll('.answer')];buttons.forEach((b,i)=>{b.disabled=true;if(i===secretAnswer)b.classList.add('correct');if(i===selected&&i!==secretAnswer)b.classList.add('wrong')});const fb=document.getElementById('feedback');fb.style.display='block';attempts[guesser]++;if(selected===secretAnswer){score[guesser]++;fb.className='feedback good';fb.textContent='إجابة صح! +1 نقطة حب 💚';showReaction(true)}else{fb.className='feedback bad';fb.textContent='مش هي! الإجابة الصحيحة ملوّنة بالأخضر 💗';showReaction(false)}updateScores();setMainButton(index===deck.length-1?'شوفوا النتيجة 🏆':'السؤال التالي 💕',true);}
function localNext(){index++;if(index>=deck.length){showResult();return}owner=1-owner;guesser=1-owner;renderLocalOwner();}

function showJoin(){document.getElementById('joinBox').style.display='block';document.getElementById('joinCode').focus();}
function randomCode(){return String(Math.floor(100000+Math.random()*900000));}
function peerId(code){return 'haltaarifni-'+code;}
function onlineName(){return document.getElementById('onlineName').value.trim()||'حبيبك';}
function setRoomStatus(text,kind=''){const s=document.getElementById('roomStatus');s.textContent=text;s.className='status '+kind;}
function createRoom(){if(typeof Peer==='undefined'){alert('تعذر تحميل خدمة الاتصال. تأكد من وجود إنترنت.');return}cleanupPeer();playMode='online';isHost=true;myIndex=0;p1=onlineName();p2='الطرف الثاني';roomCode=randomCode();showScreen('lobby');document.getElementById('roomCodeView').textContent=roomCode;document.getElementById('lobbyTitle').textContent='غرفتك جاهزة 💕';document.getElementById('lobbyHint').textContent='أرسل الكود أو رابط الدعوة للطرف الثاني.';document.getElementById('hostOptions').style.display='block';setRoomStatus('جاري فتح الغرفة...');openHostPeer();}
function openHostPeer(){peer=new Peer(peerId(roomCode));peer.on('open',()=>setRoomStatus('الغرفة مفتوحة — بانتظار الطرف الثاني...'));peer.on('connection',c=>{if(conn&&conn.open){c.close();return}conn=c;bindConnection(true)});peer.on('error',e=>{if(e.type==='unavailable-id'){roomCode=randomCode();document.getElementById('roomCodeView').textContent=roomCode;try{peer.destroy()}catch(_){}openHostPeer()}else setRoomStatus('تعذر فتح الغرفة: '+e.type,'bad')});}
function joinRoom(){if(typeof Peer==='undefined'){alert('تعذر تحميل خدمة الاتصال. تأكد من وجود إنترنت.');return}const code=document.getElementById('joinCode').value.replace(/\D/g,'').slice(0,6);if(code.length!==6){alert('أدخل كود من 6 أرقام');return}cleanupPeer();playMode='online';isHost=false;myIndex=1;p2=onlineName();p1='الطرف الأول';roomCode=code;showScreen('lobby');document.getElementById('roomCodeView').textContent=roomCode;document.getElementById('lobbyTitle').textContent='جاري دخول الغرفة 💞';document.getElementById('lobbyHint').textContent='نحاول الاتصال بصاحب الغرفة.';document.getElementById('hostOptions').style.display='none';setRoomStatus('جاري الاتصال...');peer=new Peer();peer.on('open',()=>{conn=peer.connect(peerId(roomCode),{reliable:true});bindConnection(false)});peer.on('error',e=>setRoomStatus('مشكلة في الاتصال: '+e.type,'bad'));}
function bindConnection(hostSide){conn.on('open',()=>{connected=true;setRoomStatus('تم الاتصال 💚','ok');if(!hostSide)send({type:'hello',name:p2})});conn.on('data',handleMessage);conn.on('close',()=>{connected=false;showWaiting('انقطع الاتصال','خرج الطرف الثاني من الغرفة. ارجع للرئيسية وأنشئوا غرفة جديدة.','💔')});conn.on('error',()=>setRoomStatus('حدث خطأ في الاتصال','bad'));}
function send(data){if(conn&&conn.open)conn.send(data)}
function handleMessage(m){if(!m||!m.type)return;
  if(isHost&&m.type==='hello'){p2=m.name||'الطرف الثاني';setRoomStatus('اتصل '+p2+' 💚','ok');document.getElementById('onlineStartBtn').disabled=false;document.getElementById('onlineStartBtn').textContent='ابدأ الجولة الآن 💘';send({type:'ready',names:[p1,p2]});return}
  if(!isHost&&m.type==='ready'){p1=m.names[0];p2=m.names[1];setRoomStatus('تم الاتصال مع '+p1+' 💚','ok');return}
  if(m.type==='start'){p1=m.names[0];p2=m.names[1];deck=m.deck;score=[0,0];attempts=[0,0];index=0;owner=m.owner;guesser=1-owner;showScreen('game');renderOnlinePhase('owner');return}
  if(isHost&&m.type==='secret'){if(onlinePhase!=='owner')return;secretAnswer=m.value;onlinePhase='guess';send({type:'phase',phase:'guess',index,owner,guesser});renderOnlinePhase('guess');return}
  if(!isHost&&m.type==='phase'){owner=m.owner;guesser=m.guesser;renderOnlinePhase(m.phase);return}
  if(isHost&&m.type==='guess'){if(onlinePhase!=='guess')return;finishOnlineGuess(m.value);return}
  if(m.type==='result'){score=m.score;attempts=m.attempts||attempts;renderOnlineResult(m.guess,m.correct);return}
  if(isHost&&m.type==='next'){advanceOnline();return}
  if(!isHost&&m.type==='nextstate'){index=m.index;owner=m.owner;guesser=m.guesser;renderOnlinePhase('owner');return}
  if(m.type==='final'){score=m.score;attempts=m.attempts||attempts;showResult();return}
}
function hostStartOnline(){if(!connected)return;const mode=document.getElementById('onlineMode').value,size=+document.getElementById('onlineSize').value,pool=mode==='all'?bank:bank.filter(x=>x.c===mode);deck=getFreshDeck(pool,Math.min(size,pool.length));score=[0,0];attempts=[0,0];index=0;owner=Math.random()<.5?0:1;guesser=1-owner;onlinePhase='owner';send({type:'start',names:[p1,p2],deck,owner});showScreen('game');renderOnlinePhase('owner');}
function renderOnlinePhase(phase){onlinePhase=phase;stage=phase;selected=null;secretAnswer=isHost?secretAnswer:null;updateScores();const me=myIndex;const ownerName=owner===0?p1:p2,guessName=guesser===0?p1:p2;setTurn(phase==='owner'?'💞 دور <strong>'+esc(ownerName)+'</strong> الآن — السؤال '+(index+1)+' من '+deck.length:'💭 دور <strong>'+esc(guessName)+'</strong> للتخمين — السؤال '+(index+1)+' من '+deck.length);
  if(phase==='owner'){
    if(me===owner){showQuestionStage();document.getElementById('stepBadge').textContent='إجابتك السرّية 🔒';document.getElementById('question').textContent=deck[index].q;document.getElementById('instruction').innerHTML='اختار/ي إجابتك الحقيقية. <strong>'+esc(guessName)+'</strong> لن يراها.';renderAnswers(true);setMainButton('ثبّت إجابتي 🔒',false);}
    else{showWaiting('دور '+ownerName,'بانتظار <strong>'+esc(ownerName)+'</strong> يختار إجابته السرّية...','🤫💗')}
  } else if(phase==='guess'){
    if(me===guesser){showQuestionStage();document.getElementById('stepBadge').textContent='خمن الإجابة 💭';document.getElementById('question').textContent=deck[index].q;document.getElementById('instruction').innerHTML='أي إجابة تتوقع/ي أن <strong>'+esc(ownerName)+'</strong> اختارها؟';renderAnswers(true);setMainButton('أكد التخمين 💘',false);}
    else{showWaiting('تم حفظ إجابتك','الآن <strong>'+esc(guessName)+'</strong> يحاول يعرف إجابتك...','💭💕')}
  }
}
function onlineSubmitOwner(){if(myIndex!==owner)return;if(selected===null){needChoice();return}if(isHost){secretAnswer=selected;onlinePhase='guess';send({type:'phase',phase:'guess',index,owner,guesser});renderOnlinePhase('guess')}else{send({type:'secret',value:selected});showWaiting('تم إرسال إجابتك','بانتظار تخمين '+esc(p1)+'...','💌')}}
function onlineSubmitGuess(){if(myIndex!==guesser)return;if(selected===null){needChoice();return}if(isHost)finishOnlineGuess(selected);else{send({type:'guess',value:selected});showWaiting('تم إرسال التخمين','بانتظار النتيجة...','💘')}}
function finishOnlineGuess(guess){const correct=secretAnswer;attempts[guesser]++;if(guess===correct)score[guesser]++;onlinePhase='result';send({type:'result',guess,correct,score,attempts});renderOnlineResult(guess,correct);}
function renderOnlineResult(guess,correct){onlinePhase='result';stage='result';selected=guess;showQuestionStage();setTurn(guess===correct?'❤️ نقطة حب جديدة!':'💗 خلّوها للسؤال الجاي');showReaction(guess===correct);document.getElementById('stepBadge').textContent='النتيجة 💞';document.getElementById('question').textContent=deck[index].q;document.getElementById('instruction').textContent=guess===correct?'إجابة صحيحة! 🎉':'الإجابة الصحيحة ظهرت بالأخضر.';renderAnswers(false);[...document.querySelectorAll('.answer')].forEach((b,i)=>{if(i===correct)b.classList.add('correct');if(i===guess&&guess!==correct)b.classList.add('wrong')});const fb=document.getElementById('feedback');fb.style.display='block';fb.className='feedback '+(guess===correct?'good':'bad');fb.textContent=guess===correct?'عرفها! +1 نقطة حب 💚':'هذه المرة ما عرفها 💗';updateScores();setMainButton(index===deck.length-1?'شوفوا النتيجة 🏆':'السؤال التالي 💕',true);}
function requestOnlineNext(){if(isHost)advanceOnline();else{send({type:'next'});showWaiting('لحظة واحدة','ننتقل للسؤال التالي...','💕')}}
function advanceOnline(){if(onlinePhase!=='result')return;index++;if(index>=deck.length){send({type:'final',score,attempts});showResult();return}owner=1-owner;guesser=1-owner;secretAnswer=null;onlinePhase='owner';send({type:'nextstate',index,owner,guesser});renderOnlinePhase('owner');}

function mainAction(){if(playMode==='local'){if(stage==='owner')localLock();else if(stage==='guess')localCheck();else localNext();return}const phase=onlinePhase||stage;if(phase==='owner')onlineSubmitOwner();else if(phase==='guess')onlineSubmitGuess();else if(phase==='result')requestOnlineNext();}
function showResult(){showScreen('result');const pct1=Math.round((score[0]/Math.max(1,attempts[0]))*100),pct2=Math.round((score[1]/Math.max(1,attempts[1]))*100);document.getElementById('r1name').textContent=p1+' يعرف '+p2;document.getElementById('r2name').textContent=p2+' يعرف '+p1;document.getElementById('r1pct').textContent=pct1+'%';document.getElementById('r2pct').textContent=pct2+'%';document.getElementById('r1detail').textContent=score[0]+' من '+attempts[0]+' تخمين صحيح';document.getElementById('r2detail').textContent=score[1]+' من '+attempts[1]+' تخمين صحيح';const w=document.getElementById('winnerText'),sub=document.getElementById('resultSub'),heart=document.getElementById('heartWinner');if(pct1>pct2){w.textContent='👑 الفائز بقلب الجولة: '+p1+' ❤️';sub.textContent=p1+' عرف إجابات '+p2+' بنسبة أعلى في هذه الجولة.';heart.textContent='💘 '+p1+' جمع نقاط حب أكثر في تحدّي المعرفة!'}else if(pct2>pct1){w.textContent='👑 الفائز بقلب الجولة: '+p2+' ❤️';sub.textContent=p2+' عرف إجابات '+p1+' بنسبة أعلى في هذه الجولة.';heart.textContent='💘 '+p2+' جمع نقاط حب أكثر في تحدّي المعرفة!'}else{w.textContent='💞 قلب الجولة مناصفة!';sub.textContent='نسبة معرفتكم ببعض متساوية في هذه الجولة.';heart.textContent='❤️ تعادل رومانسي — جولة ثانية تحسم التحدّي!'}const totalAttempts=attempts[0]+attempts[1],totalCorrect=score[0]+score[1],pct=Math.round((totalCorrect/Math.max(1,totalAttempts))*100);setTimeout(()=>document.getElementById('meterFill').style.width=Math.max(6,pct)+'%',120);document.getElementById('meterText').textContent='عرفتوا '+totalCorrect+' من '+totalAttempts+' إجابة بشكل صحيح — '+pct+'% تفاهم في الجولة.';burstHearts();}
function burstHearts(){const box=document.getElementById('confetti');box.innerHTML='';const icons=['💗','💖','💕','✨','💘','💜'];for(let i=0;i<34;i++){const el=document.createElement('i');el.textContent=icons[Math.floor(Math.random()*icons.length)];el.style.left=(Math.random()*100)+'vw';el.style.fontSize=(16+Math.random()*20)+'px';el.style.animationDelay=(Math.random()*1.1)+'s';el.style.animationDuration=(2.8+Math.random()*2)+'s';box.appendChild(el)}setTimeout(()=>box.innerHTML='',5200)}
function inviteLink(){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('room',roomCode);return u.toString();}
function copyText(text,ok){if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(text).then(()=>setRoomStatus(ok,'ok')).catch(()=>fallbackCopy(text,ok));}else fallbackCopy(text,ok);}
function fallbackCopy(text,ok){const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();try{document.execCommand('copy');setRoomStatus(ok,'ok')}catch(e){prompt('انسخ النص:',text)}t.remove();}
function copyRoomCode(){copyText(roomCode,'تم نسخ الكود 💕')}
function copyInviteLink(){copyText(inviteLink(),'تم نسخ رابط الدعوة 💌')}
function shareRoom(){const url=inviteLink(),text='تعال/ي نلعب هل تعرفني؟ ❤️\nكود الغرفة: '+roomCode;if(navigator.share)navigator.share({title:'هل تعرفني؟',text,url}).catch(()=>{});else copyInviteLink();}
function applyInviteFromUrl(){const code=new URLSearchParams(location.search).get('room');if(code&&/^\d{6}$/.test(code)){showScreen('onlineSetup');document.getElementById('joinBox').style.display='block';document.getElementById('joinCode').value=code;setTimeout(()=>document.getElementById('onlineName').focus(),150);}}
window.addEventListener('DOMContentLoaded',()=>{const main=document.getElementById('mainBtn');if(main)main.addEventListener('click',mainAction);applyInviteFromUrl();});
window.addEventListener('beforeunload',()=>cleanupPeer());
